/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AddPlaceDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-19T00:57:09.000-05:00")
public class AddPlaceDTO {
  @SerializedName("address")
  private String address = null;

  @SerializedName("latitude")
  private Float latitude = null;

  @SerializedName("longitude")
  private Float longitude = null;

  @SerializedName("name")
  private String name = null;

  public AddPlaceDTO address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Full address and city name of the place
   * @return address
  **/
  @ApiModelProperty(value = "Full address and city name of the place")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public AddPlaceDTO latitude(Float latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Place&#39;s geographic coordinate
   * @return latitude
  **/
  @ApiModelProperty(value = "Place's geographic coordinate")
  public Float getLatitude() {
    return latitude;
  }

  public void setLatitude(Float latitude) {
    this.latitude = latitude;
  }

  public AddPlaceDTO longitude(Float longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Place&#39;s geographic coordinate
   * @return longitude
  **/
  @ApiModelProperty(value = "Place's geographic coordinate")
  public Float getLongitude() {
    return longitude;
  }

  public void setLongitude(Float longitude) {
    this.longitude = longitude;
  }

  public AddPlaceDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the place
   * @return name
  **/
  @ApiModelProperty(value = "Name of the place")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddPlaceDTO addPlaceDTO = (AddPlaceDTO) o;
    return Objects.equals(this.address, addPlaceDTO.address) &&
        Objects.equals(this.latitude, addPlaceDTO.latitude) &&
        Objects.equals(this.longitude, addPlaceDTO.longitude) &&
        Objects.equals(this.name, addPlaceDTO.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, latitude, longitude, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddPlaceDTO {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

