/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AddPollutantDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-18T23:27:07.769-05:00")
public class AddPollutantDTO {
  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("units")
  private String units = null;

  public AddPollutantDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Pollutant&#39;s description
   * @return description
  **/
  @ApiModelProperty(value = "Pollutant's description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AddPollutantDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full name of the pollutant
   * @return name
  **/
  @ApiModelProperty(value = "Full name of the pollutant")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AddPollutantDTO symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Pollutant&#39;s symbol
   * @return symbol
  **/
  @ApiModelProperty(value = "Pollutant's symbol")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public AddPollutantDTO units(String units) {
    this.units = units;
    return this;
  }

   /**
   * Pollutant&#39;s units of measurement
   * @return units
  **/
  @ApiModelProperty(value = "Pollutant's units of measurement")
  public String getUnits() {
    return units;
  }

  public void setUnits(String units) {
    this.units = units;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddPollutantDTO addPollutantDTO = (AddPollutantDTO) o;
    return Objects.equals(this.description, addPollutantDTO.description) &&
        Objects.equals(this.name, addPollutantDTO.name) &&
        Objects.equals(this.symbol, addPollutantDTO.symbol) &&
        Objects.equals(this.units, addPollutantDTO.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, symbol, units);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddPollutantDTO {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

