/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * AddUserProfileDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-18T23:27:07.769-05:00")
public class AddUserProfileDTO {
  @SerializedName("bio")
  private String bio = null;

  @SerializedName("birthday")
  private DateTime birthday = null;

  @SerializedName("country")
  private Integer country = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("profilePicture")
  private String profilePicture = null;

  @SerializedName("timezone")
  private Integer timezone = null;

  @SerializedName("url")
  private String url = null;

  public AddUserProfileDTO bio(String bio) {
    this.bio = bio;
    return this;
  }

   /**
   * Brief user&#39;s description
   * @return bio
  **/
  @ApiModelProperty(value = "Brief user's description")
  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public AddUserProfileDTO birthday(DateTime birthday) {
    this.birthday = birthday;
    return this;
  }

   /**
   * User&#39;s birthday: YYYY-MM-DDTHH:mm:ss.GTM or value in milliseconds
   * @return birthday
  **/
  @ApiModelProperty(value = "User's birthday: YYYY-MM-DDTHH:mm:ss.GTM or value in milliseconds")
  public DateTime getBirthday() {
    return birthday;
  }

  public void setBirthday(DateTime birthday) {
    this.birthday = birthday;
  }

  public AddUserProfileDTO country(Integer country) {
    this.country = country;
    return this;
  }

   /**
   * User&#39;s residence
   * @return country
  **/
  @ApiModelProperty(value = "User's residence")
  public Integer getCountry() {
    return country;
  }

  public void setCountry(Integer country) {
    this.country = country;
  }

  public AddUserProfileDTO lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * User&#39;s lastname
   * @return lastname
  **/
  @ApiModelProperty(value = "User's lastname")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public AddUserProfileDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * User&#39;s name
   * @return name
  **/
  @ApiModelProperty(value = "User's name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AddUserProfileDTO profilePicture(String profilePicture) {
    this.profilePicture = profilePicture;
    return this;
  }

   /**
   * User profile pictre URL
   * @return profilePicture
  **/
  @ApiModelProperty(value = "User profile pictre URL")
  public String getProfilePicture() {
    return profilePicture;
  }

  public void setProfilePicture(String profilePicture) {
    this.profilePicture = profilePicture;
  }

  public AddUserProfileDTO timezone(Integer timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Country time zone
   * @return timezone
  **/
  @ApiModelProperty(value = "Country time zone")
  public Integer getTimezone() {
    return timezone;
  }

  public void setTimezone(Integer timezone) {
    this.timezone = timezone;
  }

  public AddUserProfileDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * User profile URL
   * @return url
  **/
  @ApiModelProperty(value = "User profile URL")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddUserProfileDTO addUserProfileDTO = (AddUserProfileDTO) o;
    return Objects.equals(this.bio, addUserProfileDTO.bio) &&
        Objects.equals(this.birthday, addUserProfileDTO.birthday) &&
        Objects.equals(this.country, addUserProfileDTO.country) &&
        Objects.equals(this.lastname, addUserProfileDTO.lastname) &&
        Objects.equals(this.name, addUserProfileDTO.name) &&
        Objects.equals(this.profilePicture, addUserProfileDTO.profilePicture) &&
        Objects.equals(this.timezone, addUserProfileDTO.timezone) &&
        Objects.equals(this.url, addUserProfileDTO.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bio, birthday, country, lastname, name, profilePicture, timezone, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddUserProfileDTO {\n");
    
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    profilePicture: ").append(toIndentedString(profilePicture)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

