/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * AddValuesToMeasurementDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-18T23:27:07.769-05:00")
public class AddValuesToMeasurementDTO {
  @SerializedName("average")
  private Float average = null;

  @SerializedName("data")
  private Map<String, Float> data = null;

  @SerializedName("pollutantId")
  private Integer pollutantId = null;

  public AddValuesToMeasurementDTO average(Float average) {
    this.average = average;
    return this;
  }

   /**
   * Get average
   * @return average
  **/
  @ApiModelProperty(value = "")
  public Float getAverage() {
    return average;
  }

  public void setAverage(Float average) {
    this.average = average;
  }

  public AddValuesToMeasurementDTO data(Map<String, Float> data) {
    this.data = data;
    return this;
  }

  public AddValuesToMeasurementDTO putDataItem(String key, Float dataItem) {
    if (this.data == null) {
      this.data = new HashMap<String, Float>();
    }
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public Map<String, Float> getData() {
    return data;
  }

  public void setData(Map<String, Float> data) {
    this.data = data;
  }

  public AddValuesToMeasurementDTO pollutantId(Integer pollutantId) {
    this.pollutantId = pollutantId;
    return this;
  }

   /**
   * Get pollutantId
   * @return pollutantId
  **/
  @ApiModelProperty(value = "")
  public Integer getPollutantId() {
    return pollutantId;
  }

  public void setPollutantId(Integer pollutantId) {
    this.pollutantId = pollutantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddValuesToMeasurementDTO addValuesToMeasurementDTO = (AddValuesToMeasurementDTO) o;
    return Objects.equals(this.average, addValuesToMeasurementDTO.average) &&
        Objects.equals(this.data, addValuesToMeasurementDTO.data) &&
        Objects.equals(this.pollutantId, addValuesToMeasurementDTO.pollutantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(average, data, pollutantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddValuesToMeasurementDTO {\n");
    
    sb.append("    average: ").append(toIndentedString(average)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    pollutantId: ").append(toIndentedString(pollutantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

