/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MeasurementDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MeasurementsDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-19T00:57:09.000-05:00")
public class MeasurementsDTO {
  @SerializedName("measurements")
  private List<MeasurementDTO> measurements = null;

  public MeasurementsDTO measurements(List<MeasurementDTO> measurements) {
    this.measurements = measurements;
    return this;
  }

  public MeasurementsDTO addMeasurementsItem(MeasurementDTO measurementsItem) {
    if (this.measurements == null) {
      this.measurements = new ArrayList<MeasurementDTO>();
    }
    this.measurements.add(measurementsItem);
    return this;
  }

   /**
   * List of measurements
   * @return measurements
  **/
  @ApiModelProperty(value = "List of measurements")
  public List<MeasurementDTO> getMeasurements() {
    return measurements;
  }

  public void setMeasurements(List<MeasurementDTO> measurements) {
    this.measurements = measurements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasurementsDTO measurementsDTO = (MeasurementsDTO) o;
    return Objects.equals(this.measurements, measurementsDTO.measurements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasurementsDTO {\n");
    
    sb.append("    measurements: ").append(toIndentedString(measurements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

