/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PlaceDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PlacesDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-19T00:57:09.000-05:00")
public class PlacesDTO {
  @SerializedName("places")
  private List<PlaceDTO> places = null;

  public PlacesDTO places(List<PlaceDTO> places) {
    this.places = places;
    return this;
  }

  public PlacesDTO addPlacesItem(PlaceDTO placesItem) {
    if (this.places == null) {
      this.places = new ArrayList<PlaceDTO>();
    }
    this.places.add(placesItem);
    return this;
  }

   /**
   * List of places
   * @return places
  **/
  @ApiModelProperty(value = "List of places")
  public List<PlaceDTO> getPlaces() {
    return places;
  }

  public void setPlaces(List<PlaceDTO> places) {
    this.places = places;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacesDTO placesDTO = (PlacesDTO) o;
    return Objects.equals(this.places, placesDTO.places);
  }

  @Override
  public int hashCode() {
    return Objects.hash(places);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacesDTO {\n");
    
    sb.append("    places: ").append(toIndentedString(places)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

