/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserProfileDTO;
import java.io.IOException;

/**
 * UserDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-18T23:27:07.769-05:00")
public class UserDTO {
  @SerializedName("email")
  private String email = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("profile")
  private UserProfileDTO profile = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("username")
  private String username = null;

  public UserDTO email(String email) {
    this.email = email;
    return this;
  }

   /**
   * User&#39;s email
   * @return email
  **/
  @ApiModelProperty(value = "User's email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Autogenerated user id
   * @return id
  **/
  @ApiModelProperty(value = "Autogenerated user id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UserDTO profile(UserProfileDTO profile) {
    this.profile = profile;
    return this;
  }

   /**
   * User&#39;s Profile information
   * @return profile
  **/
  @ApiModelProperty(value = "User's Profile information")
  public UserProfileDTO getProfile() {
    return profile;
  }

  public void setProfile(UserProfileDTO profile) {
    this.profile = profile;
  }

  public UserDTO state(String state) {
    this.state = state;
    return this;
  }

   /**
   * User&#39;s state. UNVERIFIED, ACTIVE, INATIVE or BANNED
   * @return state
  **/
  @ApiModelProperty(value = "User's state. UNVERIFIED, ACTIVE, INATIVE or BANNED")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public UserDTO username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Login name in the web and mobile apps
   * @return username
  **/
  @ApiModelProperty(value = "Login name in the web and mobile apps")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDTO userDTO = (UserDTO) o;
    return Objects.equals(this.email, userDTO.email) &&
        Objects.equals(this.id, userDTO.id) &&
        Objects.equals(this.profile, userDTO.profile) &&
        Objects.equals(this.state, userDTO.state) &&
        Objects.equals(this.username, userDTO.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, id, profile, state, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDTO {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

