/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CountryDTO;
import io.swagger.client.model.TimezoneDTO;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * UserProfileDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-19T00:57:09.000-05:00")
public class UserProfileDTO {
  @SerializedName("bio")
  private String bio = null;

  @SerializedName("birthday")
  private DateTime birthday = null;

  @SerializedName("country")
  private CountryDTO country = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("profilePicture")
  private String profilePicture = null;

  @SerializedName("timezone")
  private TimezoneDTO timezone = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("userId")
  private String userId = null;

  public UserProfileDTO bio(String bio) {
    this.bio = bio;
    return this;
  }

   /**
   * Brief user&#39;s description
   * @return bio
  **/
  @ApiModelProperty(value = "Brief user's description")
  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public UserProfileDTO birthday(DateTime birthday) {
    this.birthday = birthday;
    return this;
  }

   /**
   * User&#39;s birthday: YYYY-MM-DDTHH:mm:ss.GTM or value in milliseconds
   * @return birthday
  **/
  @ApiModelProperty(value = "User's birthday: YYYY-MM-DDTHH:mm:ss.GTM or value in milliseconds")
  public DateTime getBirthday() {
    return birthday;
  }

  public void setBirthday(DateTime birthday) {
    this.birthday = birthday;
  }

  public UserProfileDTO country(CountryDTO country) {
    this.country = country;
    return this;
  }

   /**
   * User&#39;s residence
   * @return country
  **/
  @ApiModelProperty(value = "User's residence")
  public CountryDTO getCountry() {
    return country;
  }

  public void setCountry(CountryDTO country) {
    this.country = country;
  }

  public UserProfileDTO lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * User&#39;s lastname
   * @return lastname
  **/
  @ApiModelProperty(value = "User's lastname")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public UserProfileDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * User&#39;s name
   * @return name
  **/
  @ApiModelProperty(value = "User's name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserProfileDTO profilePicture(String profilePicture) {
    this.profilePicture = profilePicture;
    return this;
  }

   /**
   * User profile pictre URL
   * @return profilePicture
  **/
  @ApiModelProperty(value = "User profile pictre URL")
  public String getProfilePicture() {
    return profilePicture;
  }

  public void setProfilePicture(String profilePicture) {
    this.profilePicture = profilePicture;
  }

  public UserProfileDTO timezone(TimezoneDTO timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Country time zone
   * @return timezone
  **/
  @ApiModelProperty(value = "Country time zone")
  public TimezoneDTO getTimezone() {
    return timezone;
  }

  public void setTimezone(TimezoneDTO timezone) {
    this.timezone = timezone;
  }

  public UserProfileDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * User profile URL
   * @return url
  **/
  @ApiModelProperty(value = "User profile URL")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public UserProfileDTO userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfileDTO userProfileDTO = (UserProfileDTO) o;
    return Objects.equals(this.bio, userProfileDTO.bio) &&
        Objects.equals(this.birthday, userProfileDTO.birthday) &&
        Objects.equals(this.country, userProfileDTO.country) &&
        Objects.equals(this.lastname, userProfileDTO.lastname) &&
        Objects.equals(this.name, userProfileDTO.name) &&
        Objects.equals(this.profilePicture, userProfileDTO.profilePicture) &&
        Objects.equals(this.timezone, userProfileDTO.timezone) &&
        Objects.equals(this.url, userProfileDTO.url) &&
        Objects.equals(this.userId, userProfileDTO.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bio, birthday, country, lastname, name, profilePicture, timezone, url, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfileDTO {\n");
    
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    profilePicture: ").append(toIndentedString(profilePicture)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

