/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorDTO;
import io.swagger.client.model.MeasurementDataDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataControllerApi
 */
@Ignore
public class DataControllerApiTest {

    private final DataControllerApi api = new DataControllerApi();

    
    /**
     * Get measurement data
     *
     * Fetch a measurement data.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMeasurementPollutantDataUsingGETTest() throws ApiException {
        Integer measurementId = null;
        Integer pollutantId = null;
        MeasurementDataDTO response = api.getMeasurementPollutantDataUsingGET(measurementId, pollutantId);

        // TODO: test validations
    }
    
}
