/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionControllerApi
 */
@Ignore
public class TransactionControllerApiTest {

    private final TransactionControllerApi api = new TransactionControllerApi();

    
    /**
     * Handle transaction
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTransactionUsingPOSTTest() throws ApiException {
        Integer statePol = null;
        String referenceSale = null;
        String referencePol = null;
        String sign = null;
        Double value = null;
        Boolean test = null;
        api.createTransactionUsingPOST(statePol, referenceSale, referencePol, sign, value, test);

        // TODO: test validations
    }
    
}
