/*
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.4
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorDTO;
import io.swagger.client.model.UserProfileDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserProfileControllerApi
 */
@Ignore
public class UserProfileControllerApiTest {

    private final UserProfileControllerApi api = new UserProfileControllerApi();

    
    /**
     * Edit a user profile
     *
     * Edit a user profile by a given user id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editUserProfileUsingPUTTest() throws ApiException {
        UserProfileDTO userProfileDTO = null;
        api.editUserProfileUsingPUT(userProfileDTO);

        // TODO: test validations
    }
    
    /**
     * Get user profile
     *
     * Get a user profile by a given user id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserProfileUsingGETTest() throws ApiException {
        String id = null;
        UserProfileDTO response = api.getUserProfileUsingGET(id);

        // TODO: test validations
    }
    
}
